import type { PersistedAppState, RuntimeDetection } from "../types";

const now = new Date();
const minutesAgo = (minutes: number) => new Date(now.getTime() - minutes * 60_000).toISOString();

export const demoDetection: RuntimeDetection = {
  installed: true,
  version: "0.7.4",
  executable: "prime-agent",
  mode: "system",
  configDir: "~/.prime/agent",
  prerequisites: [
    { name: "Prime Agent", found: true, version: "0.7.4" },
    { name: "Node.js", found: true, version: "22.17.0" },
    { name: "Python", found: true, version: "3.13.7" },
    { name: "Git", found: true, version: "2.51.0" },
  ],
};

export const defaultAppState: PersistedAppState = {
  version: 2,
  projects: [],
  conversations: [],
  preferences: {
    theme: "dark",
    language: "fr",
    restoreLastWorkspace: false,
    automaticUpdateChecks: true,
    compactSidebar: false,
    inspectorOpen: true,
    bottomDockOpen: false,
    telemetry: false,
    defaultThinking: "high",
    defaultPermissionPreset: "standard",
    reduceMotion: false,
  },
};

export const demoAppState: PersistedAppState = {
  ...defaultAppState,
  projects: [
    {
      id: "project-prime-orbit",
      name: "prime-agent-gui",
      path: "C:\\Projects\\prime-orbit",
      color: "#7c6cff",
      createdAt: minutesAgo(960),
      lastOpenedAt: minutesAgo(2),
      pinned: true,
      permissionPreset: "standard",
      defaultModel: "ollama/qwen3.8-27b-dev:latest",
    },
    {
      id: "project-rally",
      name: "Rally Protocol",
      path: "C:\\Projects\\sample-app",
      color: "#45c6d8",
      createdAt: minutesAgo(4_200),
      lastOpenedAt: minutesAgo(180),
      pinned: false,
      permissionPreset: "guarded",
    },
  ],
  conversations: [
    {
      id: "conversation-orbit",
      projectId: "project-prime-orbit",
      title: "Concevoir Prime Orbit",
      createdAt: minutesAgo(42),
      updatedAt: minutesAgo(2),
      pinned: true,
      archived: false,
      status: "idle",
      model: "ollama/qwen3.8-27b-dev:latest",
      thinkingLevel: "high",
      draft: "",
      messages: [
        {
          id: "message-user-demo",
          role: "user",
          content: "Construis une interface desktop professionnelle pour Prime Agent, organisée par projets et conversations. Je veux garder toutes les fonctions avancées sans passer par le terminal.",
          createdAt: minutesAgo(40),
          status: "complete",
        },
        {
          id: "message-agent-demo",
          role: "assistant",
          content: "Le socle est prêt. L’application se connecte au mode RPC de Prime Agent : chaque conversation possède son propre processus, son dossier de travail et sa session persistante.\n\nJ’ai structuré l’expérience autour de trois couches : la conversation au centre, l’activité des outils dans l’inspecteur, et les réglages réellement pris en charge par Prime Agent accessibles sans interrompre le travail.",
          createdAt: minutesAgo(3),
          status: "complete",
          model: "qwen3.8-27b-dev",
          durationMs: 84_200,
          tools: [
            {
              id: "tool-audit",
              name: "ipython",
              title: "Analyse de l’architecture Prime Agent",
              status: "completed",
              startedAt: minutesAgo(38),
              endedAt: minutesAgo(34),
              input: "Inspection des modes RPC et daemon",
              output: "RPC JSONL disponible, sessions persistantes détectées",
            },
            {
              id: "tool-ui",
              name: "ipython",
              title: "Création de l’interface desktop",
              status: "completed",
              startedAt: minutesAgo(33),
              endedAt: minutesAgo(4),
              input: "Tauri 2 + React + TypeScript",
              output: "Navigation, conversation, modèles et inspecteur créés",
            },
          ],
          usage: { input: 18_430, output: 2_112, cacheRead: 9_840, total: 30_382 },
        },
      ],
      activities: [
        { id: "activity-1", type: "agent_start", title: "Prime Agent a démarré", detail: "Session RPC connectée", status: "success", createdAt: minutesAgo(40) },
        { id: "activity-2", type: "tool", title: "Analyse du dépôt", detail: "186 fichiers inspectés", status: "success", createdAt: minutesAgo(36) },
        { id: "activity-3", type: "tool", title: "Compilation desktop", detail: "Vérifications terminées", status: "success", createdAt: minutesAgo(3) },
      ],
    },
    {
      id: "conversation-install",
      projectId: "project-prime-orbit",
      title: "Installation rapide Windows",
      createdAt: minutesAgo(330),
      updatedAt: minutesAgo(245),
      pinned: false,
      archived: false,
      status: "idle",
      thinkingLevel: "medium",
      draft: "",
      messages: [],
      activities: [],
    },
    {
      id: "conversation-models",
      projectId: "project-prime-orbit",
      title: "Configurer les modèles locaux",
      createdAt: minutesAgo(1_220),
      updatedAt: minutesAgo(1_120),
      pinned: false,
      archived: false,
      status: "idle",
      thinkingLevel: "high",
      draft: "",
      messages: [],
      activities: [],
    },
    {
      id: "conversation-rally",
      projectId: "project-rally",
      title: "Réparer le scaffold Vite",
      createdAt: minutesAgo(4_000),
      updatedAt: minutesAgo(190),
      pinned: false,
      archived: false,
      status: "idle",
      thinkingLevel: "high",
      draft: "",
      messages: [],
      activities: [],
    },
  ],
  selectedProjectId: "project-prime-orbit",
  selectedConversationId: "conversation-orbit",
};
